apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-personapi
  name: udaconnect-personapi
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30002
  selector:
    service: udaconnect-personapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-personapi
  name: udaconnect-personapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-personapi
  template:
    metadata:
      labels:
        service: udaconnect-personapi
    spec:
      containers:
      - image: saurabhsaha91/udaconnect_personapi:latest
        name: udaconnect-personapi
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
